### ISSUE TITLE
iOS Sandbox Push not working

### ISSUE THREAD

**Issue by olheimer** [parse-community/parse-server-push-adapter#100]
Is there any issue known that push for iOS in sandbox mode doesn't work?

My config for production and development is identical. I use the same certificate. The only difference is the value for production attribute is false.

On production I do receive push notifications and for development not. I can't find any similar issue. 

ios: {
            pfx: <path to file >,
            passphrase:  <passphrase>, // optional password to your p12/PFX
            bundleId: <bundle id>,
            production: false
        }

UPDATE: When i activate verbose logging it seems to send successfully to APNs:
node-pre-gyp verb parse-server-push-adapter APNS APNS transmitted to XXX

**Comment by funkenstrahlen** [comment]
@olheimer As far as I know you need to generate differente APNS certificates for sandbox and production.
