### ISSUE TITLE
APNS  Error: cannot send any push

### ISSUE THREAD

**Issue by tjlian616** [parse-community/parse-server-push-adapter#113]
I am having trouble sending pushes ever since upgrading to parse-server 2.6.  Here is the log when I tried to send a message to an ios device.

`node-pre-gyp ERR! parse-server-push-adapter APNS VError: endpoint error: write EPROTO 140735604867968:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 80

node-pre-gyp ERR! parse-server-push-adapter APNS 140735604867968:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
node-pre-gyp ERR! parse-server-push-adapter APNS

node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.endpoint.on.err (/Users/anli/Documents/workspace_apollo/apolloParseServer/node_modules/apn/lib/protocol/endpointManager.js:69:32)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:96:13)
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.error [as _error] (/Users/anli/Documents/workspace_apollo/apolloParseServer/node_modules/apn/lib/protocol/endpoint.js:149:10)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:101:20)
node-pre-gyp ERR! parse-server-push-adapter APNS     at TLSSocket.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at onwriteError (_stream_writable.js:343:10)
node-pre-gyp ERR! parse-server-push-adapter APNS     at onwrite (_stream_writable.js:361:5)
node-pre-gyp ERR! parse-server-push-adapter APNS     at WritableState.onwrite (_stream_writable.js:90:5)
node-pre-gyp ERR! parse-server-push-adapter APNS     at fireErrorCallbacks (net.js:467:13)

node-pre-gyp ERR! parse-server-push-adapter APNS  APNS error transmitting to device %s with error %s badec30d7fce4b299ad2f05fb805e90f95f2b02e8e23e314ddf84cbd9e4cea6b { VError: endpoint error: write EPROTO 140735604867968:error:14094438:SSL 

routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 80
node-pre-gyp ERR! parse-server-push-adapter APNS 140735604867968:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:

node-pre-gyp ERR! parse-server-push-adapter APNS
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.endpoint.on.err (/Users/anli/Documents/workspace_apollo/apolloParseServer/node_modules/apn/lib/protocol/endpointManager.js:69:32)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:96:13)
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at EventEmitter.error [as _error] (/Users/anli/Documents/workspace_apollo/apolloParseServer/node_modules/apn/lib/protocol/endpoint.js:149:10)
node-pre-gyp ERR! parse-server-push-adapter APNS     at emitOne (events.js:101:20)
node-pre-gyp ERR! parse-server-push-adapter APNS     at TLSSocket.emit (events.js:188:7)
node-pre-gyp ERR! parse-server-push-adapter APNS     at onwriteError (_stream_writable.js:343:10)
node-pre-gyp ERR! parse-server-push-adapter APNS     at onwrite (_stream_writable.js:361:5)
node-pre-gyp ERR! parse-server-push-adapter APNS     at WritableState.onwrite (_stream_writable.js:90:5)
node-pre-gyp ERR! parse-server-push-adapter APNS     at fireErrorCallbacks (net.js:467:13)
node-pre-gyp ERR! parse-server-push-adapter APNS   jse_shortmsg: 'endpoint error',
node-pre-gyp ERR! parse-server-push-adapter APNS   jse_cause:
node-pre-gyp ERR! parse-server-push-adapter APNS    { Error: write EPROTO 140735604867968:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 80
node-pre-gyp ERR! parse-server-push-adapter APNS    140735604867968:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:
node-pre-gyp ERR! parse-server-push-adapter APNS
node-pre-gyp ERR! parse-server-push-adapter APNS        at exports._errnoException (util.js:1020:11)
node-pre-gyp ERR! parse-server-push-adapter APNS        at WriteWrap.afterWrite (net.js:800:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' },
node-pre-gyp ERR! parse-server-push-adapter APNS   jse_info: {},
node-pre-gyp ERR! parse-server-push-adapter APNS   message: 'endpoint error: write EPROTO 140735604867968:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 80\n140735604867968:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:\n',
node-pre-gyp ERR! parse-server-push-adapter APNS   stack: 'VError: endpoint error: write EPROTO 140735604867968:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s3_pkt.c:1494:SSL alert number 80\n140735604867968:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:../deps/openssl/openssl/ssl/s3_pkt.c:659:\n\n    at EventEmitter.endpoint.on.err (/Users/anli/Documents/workspace_apollo/apolloParseServer/node_modules/apn/lib/protocol/endpointManager.js:69:32)\n    at emitOne (events.js:96:13)\n    at EventEmitter.emit (events.js:188:7)\n    at EventEmitter.error [as _error] (/Users/anli/Documents/workspace_apollo/apolloParseServer/node_modules/apn/lib/protocol/endpoint.js:149:10)\n    at emitOne (events.js:101:20)\n    at TLSSocket.emit (events.js:188:7)\n    at onwriteError (_stream_writable.js:343:10)\n    at onwrite (_stream_writable.js:361:5)\n    at WritableState.onwrite (_stream_writable.js:90:5)\n    at fireErrorCallbacks (net.js:467:13)' }`

**Comment by flovilmart** [comment]
Please update parse server to the latest version and reopen it persists

**Comment by tjlian616** [comment]
@flovilmart 
The log above was from the latest version. I mentioned 2.6 not because I was on 2.6 but only to say that I have been having trouble with pushes since parser server 2.6.  Thanks!

**Comment by flovilmart** [comment]
Can you try setting production to `true` in your push configuration?

**Comment by jbcaveman** [comment]
Was there a solution for this type of error? I am getting something very similar: "node-pre-gyp ERR! parse-server-push-adapter APNS VError: endpoint error: write EPROTO 139811546462080:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/s3_pkt.c:1493:SSL alert number 80"

**Comment by davimacedo** [comment]
Can you please open a new issue and share more details, such as the parse server version that you are running and your parse server configuration settings?

**Comment by jbcaveman** [comment]
FYI, after some more digging, it appears this type of error is caused by improper exporting of the .p12 certificate. At least this was my case.
