### ISSUE TITLE
Delivery issues on GCM

### ISSUE THREAD

**Issue by Samigos** [parse-community/parse-server-push-adapter#119]
The last few weeks my users are complaining that they don't receive push notifications! Some do and some don't...

I'm on parse server 2.8.4 and here's my setup:
`push: {

        ios: {
          pfx: path.join(__dirname, './certificates/Certificates.p12'),
          topic: '...',
          production: true
      },
      android: {
          senderId: '...', // The Sender ID of GCM
          apiKey: '...'
      }
  }
`

I just saw that GCM is being deprecated! (it's not yet though)
Could this be the reason why?

**Comment by flovilmart** [comment]
Maybe, maybe not
