### ISSUE TITLE
Upgrade legacy FCM HTTP API to v1

### ISSUE THREAD

**Issue by yagotome** [parse-community/parse-server-push-adapter#150]
Hello!

I would like to send some properties in Push Notification payload so that I can use them for analytics in Firebase.

However, this [adapter still uses legacy FCM API](https://github.com/parse-community/node-gcm/blob/e4c36635ab1653a4fd11fb57ccbaa31c36f6c6a3/lib/constants.js#L4) which does not support those properties (such as [`name`, `fcm_options.analytics_label` etc](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#resource:-message)).

I wonder if you are thinking of [migrating to FCM HTTP v1 API](https://firebase.google.com/docs/cloud-messaging/migrate-v1) soon.

**Comment by dplewis** [comment]
@yagotome There is a PR opened for FCM v1. https://github.com/parse-community/parse-server-push-adapter/pull/116

It's been opened for a while now. Feel free to review, test, and add changes.

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server-push-adapter/issues/219
