### ISSUE TITLE
The Apple Push Notification service (APNs) will no longer support the legacy binary protocol as of November 2020

### ISSUE THREAD

**Issue by funkenstrahlen** [parse-community/parse-server-push-adapter#151]
> If you send push notifications with the legacy binary protocol, we recommend updating to the HTTP/2-based APNs provider API as soon as possible. You’ll be able to take advantage of great modern features, such as authentication with a JSON Web Token, improved error messaging, and per-notification feedback.

> The Apple Push Notification service (APNs) will no longer support the legacy binary protocol as of November 2020.

https://developer.apple.com/news/?id=11042019a

I assume we are already prepared for this change as far as I understand. Does anyone see some tasks required to do to fully support this?

**Comment by alexvenom** [comment]
Hey there!
As far as I understand, Parse already covers the new protocol which supports JWT and P8 certificates.
I have tested the P8 route myself and it worked quite well.

**Comment by funkenstrahlen** [comment]
Awesome. Great to hear.
