### ISSUE TITLE
Use proxy in GCM connection

### ISSUE THREAD

**Issue by simonegiacco** [parse-community/parse-server-push-adapter#152]
Hello,
I need to use a proxy while connecting to the fcm.googleapis.com server.

The package [parse-community/node-gcm](https://github.com/parse-community/node-gcm) supports the use of a proxy for the connection, but **parse-server-push-adapter** is not passing this configuration.

We have found the solution and will send a PR soon

**Comment by simonegiacco** [comment]
PR #153

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-server-push-adapter/pull/153
