### ISSUE TITLE
Add support for specifying target-content-id 

### ISSUE THREAD

**Issue by mman** [parse-community/parse-server-push-adapter#155]
When sending a push notification to the iOS 13 multi window app, a notification payload can specify ``target-content-id`` value that is later populated into ``UNNotificationContent`` when push notification is received and can later be used to target what app window should be brought forward when the notification is tapped.

WWDC video: https://developer.apple.com/videos/play/wwdc2019/259/
APN reference: https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification
UNNotificationContent: https://developer.apple.com/documentation/usernotifications/unnotificationcontent/3235764-targetcontentidentifier

Looks like a good and simple starter PR where target-content-id is basically populated through the same way ``mutable-content`` is.

**Comment by funkenstrahlen** [comment]
This might require adding support for this property to node-apn before this can be used here.

**Comment by mman** [comment]
This is obviously available for a very long time, closing.
