### ISSUE TITLE
Upgrade Parse from 2.8.0 to 2.10.0

### ISSUE THREAD

**Issue by gnowland** [parse-community/parse-server-push-adapter#166]
Dependency Parse should be upgraded from "2.8.0" to "2.10.0" because of security vulnerability GHSA-wvh7-5p38-2qfc affecting Parse 2.8.0

https://github.com/advisories/GHSA-wvh7-5p38-2qfc

**Comment by gnowland** [comment]
I see it has already been updated in `package.json` - perhaps release a v3.2.1 patch to push this out asap?

**Comment by davimacedo** [comment]
Let's wait for https://github.com/parse-community/node-apn/pull/18 to be merged and node-apn to be published. Then we can publish a version here as well.

**Comment by gnowland** [comment]
https://github.com/parse-community/parse-server-push-adapter/releases/tag/3.3.0 fixes this, closing.
