### ISSUE TITLE
Can't send push to Android and iOS when using alert: {... in data 

### ISSUE THREAD

**Issue by adammlevy** [parse-community/parse-server-push-adapter#212]
- [ x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-push-adapter/security/policy).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [ x] I have searched through [existing issues](https://github.com/parse-community/parse-server-push-adapter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Server Push Adapter](https://github.com/parse-community/parse-server-push-adapter/releases). 

### Issue Description
I recently changed the push data payload so that a subtitle can show up on iOS devices but that change has caused the JSON payload to show up in the push on Android devices.  This is how I'm sending the push:
```
Parse.Push.send({
            where: mainQuery,
            data: {
                alert: {
                    title : pushMessage.title,
                    subtitle: pushMessage.subtitle,
                    body: pushMessage.message
                },
                sound: pushMessage.sound,
                reportType: pushMessage.reportType,
                uri: pushMessage.uri,
                payload: pushMessage.payload	
            }
            }, {
            useMasterKey: true,
            success: function() {
               
            },
            error: function(error) {
            
                
            }
        });
```

What param to I have to pass in order to display the push properly on Android and iOS.  

### Steps to reproduce
Send a push to iOS and Android devices using the above format 

### Actual Outcome
Push gets properly sent to iOS properly but not Android 

### Expected Outcome
Push gets sent properly to both iOS and Android 

###  Environment
?

Client
- Parse Server Push Adapter version: `FILL_THIS_OUT`

Server
- Parse Server version: `2.8.4`
- Operating system: `Ubuntu`
- Local or remote host `Digital Ocean`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.0.15`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local` 

Client
- Parse JS SDK version: `1.11.0`

### Logs
None included

**Comment by mman** [comment]
I believe this should be addressed by https://github.com/parse-community/parse-server-push-adapter/pull/238.

**Comment by mman** [comment]
@adammlevy Please try https://github.com/parse-community/parse-server-push-adapter/releases/tag/6.1.1 or newer, your issue should be addressed there, and close if appropriate...

**Comment by adammlevy** [comment]
Sorry for the late response. Is it possible to upgrade to this version of the push adapter using Parse 2.8.4?

**Comment by mtrezza** [comment]
I'll go ahead and close this issue if it's already addressed by https://github.com/parse-community/parse-server-push-adapter/releases/tag/6.1.1.
