### ISSUE TITLE
Document how to configure push adapter with FCM

### ISSUE THREAD

**Issue by mman** [parse-community/parse-server-push-adapter#241]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-push-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-push-adapter/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and the [Parse Server Push Adapter](https://github.com/parse-community/parse-server-push-adapter/releases). 

### Issue Description

I had to look through code to figure out how to configure FCM.

Addressed by: https://github.com/parse-community/parse-server-push-adapter/pull/240

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server-push-adapter/releases/tag/6.3.0)
