### ISSUE TITLE
Add support for FCM http2 API

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-server-push-adapter#251]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server-push-adapter/security/policy).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/main/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server-push-adapter/issues?q=is%3Aissue).

### Current Limitation

https://github.com/parse-community/parse-server-push-adapter/issues/219 added support for the FCM HTTP v1 API, which supports HTTP/2 connectivity.

### Feature / Enhancement Description

Add support for sending push notifications via HTTP/2 connectivity when using FCM.

### 3rd Party References

- https://eladnava.com/send-multicast-notifications-using-node-js-http-2-and-the-fcm-http-v1-api/
- https://www.npmjs.com/package/fcm-v1-http2

**Comment by mtrezza** [comment]
@jimnor0xF you wrote https://github.com/parse-community/parse-server-push-adapter/issues/219#issuecomment-1685309133; could you elaborate a bit what's to do here? cc @mman

**Comment by jimnor0xF** [comment]
@mtrezza 
Unfortunately, firebase-admin-node in its current state does not use HTTP/2 under the hood at the moment. 
So we are dependent on the maintainers for that package to add support for that first.

There is a PR up: https://github.com/firebase/firebase-admin-node/pull/2550, so hopefully it is merged soon.
It probably will, since this is a pretty critical oversight on their part considering that the old API is supposed to be deprecated next month.

**Comment by mtrezza** [comment]
It seems the required PR in the firebase SDK has been merged today. https://github.com/firebase/firebase-admin-node/pull/2550

Can we already start to prepare a PR that works with that change?

**Comment by jimnor0xF** [comment]
@mtrezza 
Should be to just bump the version of the package to v12.3.0 from what I understand. Defaults to http2.

**Comment by mtrezza** [comment]
From https://github.com/firebase/firebase-admin-node/issues/2488#issuecomment-2251304450:

> This can be enabled by using the enableLegacyTransport() method. This method is already marked as deprecated and will be removed once the HTTP/2 transport is considered fully stable.

Then maybe we should expose this method as well? Or is there a way to access it?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.5.0](https://github.com/parse-community/parse-server-push-adapter/releases/tag/6.5.0)
