### ISSUE TITLE
unable to send push notification to ios devices

### ISSUE THREAD

**Issue by gowridev** [parse-community/parse-server-push-adapter#37]
I am getting below error. could you please guide me. 
App/0verb parse-server-push-adapter APNS APNS Connection 0 Socket Error2016-09-15T17:22:18.430+0530
App/0 ^2016-09-15T17:22:18.449+0530
App/0 throw err;2016-09-15T17:22:18.449+0530
App/0Error: socket hang up2016-09-15T17:22:18.451+0530
App/0 at TLSSocket.onHangUp (_tls_wrap.js:1054:19)2016-09-15T17:22:18.451+0530
App/0 at TLSSocket.g (events.js:260:16)2016-09-15T17:22:18.451+0530
App/0 at endReadableNT (_stream_readable.js:921:12)2016-09-15T17:22:18.451+0530
App/0 at emitNone (events.js:72:20)2016-09-15T17:22:18.451+0530
App/0 at nextTickCallbackWith2Args (node.js:442:9)2016-09-15T17:22:18.451+0530
App/0 at process._tickDomainCallback (node.js:397:17)2016-09-15T17:22:18.452+0530
App/0npm ERR! Linux 3.19.0-33-generic2016-09-15T17:22:18.505+0530
App/0npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"2016-09-15T17:22:18.506+0530
App/0npm ERR! node v4.5.02016-09-15T17:22:18.512+0530
App/0npm ERR! code ELIFECYCLE2016-09-15T17:22:18.516+0530
App/0 at TLSSocket.emit (events.js:166:7)2016-09-15T17:22:18.451+0530
App/0npm ERR! Exit status 72016-09-15T17:22:18.523+0530
App/0npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.2016-09-15T17:22:18.523+0530
App/0npm ERR! This is most likely a problem with the parse-server-example package,2016-09-15T17:22:18.524+0530
App/0npm ERR! not with npm itself.2016-09-15T17:22:18.525+0530
App/0npm ERR! Tell the author that this fails on your system:2016-09-15T17:22:18.526+0530
App/0npm ERR! node index.js2016-09-15T17:22:18.526+0530
App/0npm ERR! npm bugs parse-server-example2016-09-15T17:22:18.528+0530
App/0npm ERR! You can get information on how to open an issue for this project with:2016-09-15T17:22:18.527+0530
App/0npm ERR! Or if that isn't available, you can get their info via:2016-09-15T17:22:18.529+0530
App/0npm ERR! 2016-09-15T17:22:18.530+0530
App/0npm ERR! npm owner ls parse-server-example2016-09-15T17:22:18.532+0530
App/0npm ERR! There is likely additional logging output above.2016-09-15T17:22:18.532+0530
App/0npm ERR! 2016-09-15T17:22:18.523+0530
App/0npm ERR! Please include the following file with any support request:2016-09-15T17:22:18.543+0530
App/0npm ERR! /home/vcap/app/npm-debug.log2016-09-15T17:22:18.544+0530
App/0npm ERR! npm v2.15.9

**Comment by natanrolnik** [comment]
When this happens? What is your environment? What are you trying to do: start the server or trigger a push?

**Comment by gowridev** [comment]
At time of start the server. 

I sent a curl command 
curl -i -X POST \
-H "X-Parse-Application-Id: 9vEs0Z6di8uz*****" \
-H "X-Parse-Master-Key: 9O54LhBKV8oBg******" \
-H "Content-Type: application/json" \
-d '{
      "where": {
        "deviceType": "ios"
      },
      "data": {
        "title": "The Shining",
        "alert": "All work and no play makes Jack a dull boy."
      }
    }'\   https://parse-server-chatterserverv2.eu-gb.mybluemix.net/parse/push


I got this message in the console.

DEBUG=aps VERBOSE=1 node index.js
parse-server-example running on port 1337.
started scheduler
verbose: REQUEST for [POST] /parse/push: {
  "where": {
    "deviceType": "ios"
  },
  "data": {
    "title": "The Shining",
    "alert": "All work and no play makes Jack a dull boy."
  }
} method=POST, url=/parse/push, host=localhost:1337, user-agent=curl/7.43.0, accept=*/*, x-parse-application-id=9vEs0Z6di8uzmPsqr***, x-parse-master-key=9O54LhBKV8oBg0th6***, content-type=application/json, content-length=181, deviceType=ios, title=The Shining, alert=All work and no play makes Jack a dull boy.
verbose: RESPONSE from [POST] /parse/push: {
  "headers": {
    "X-Parse-Push-Status-Id": "23p1syQqQX"
  },
  "response": {
    "result": true
  }
} X-Parse-Push-Status-Id=23p1syQqQX, result=true
verbose: sending push to 1 installations
verb parse-server-push-adapter APNS APNS Connection 0 Socket Error
verb parse-server-push-adapter APNS APNS Connection 0 Disconnected
verb parse-server-push-adapter APNS APNS Connection 0 Socket Error
verb parse-server-push-adapter APNS APNS Connection 0 Disconnected
verb parse-server-push-adapter APNS APNS Connection 0 Socket Error
verb parse-server-push-adapter APNS APNS Connection 0 Disconnected
verb parse-server-push-adapter APNS APNS Connection 0 Socket Error
verb parse-server-push-adapter APNS APNS Connection 0 Disconnected
verb parse-server-push-adapter APNS APNS Connection 0 Socket Error

**Comment by mtrezza** [comment]
Closing as outdated
