### ISSUE TITLE
Support for progressive web apps

### ISSUE THREAD

**Issue by tejpratap46** [parse-community/parse-server-push-adapter#68]
Can this support web push for progressive web apps.

**Web push uses following package:**

> [web push github](https://github.com/web-push-libs/web-push)

**Service worker gives following data if user agreed to receive push notification:**
```
{
            keys: {
                auth: "rhho****************cpNnXHA==",
                p256dh: "BLna57U_B28G0wgR8A4WIr4W***********************************PbVlalFB0GaaWJhxcnP_D8="
            },
            endpoint: "https://android.googleapis.com/gcm/send/cFiMEq3HtA0:APA91bE_*********************************************************************ybpiTP_We299husGnP-sc8i9C"
}
```

I do not know how this will integrate with existing system. But, it will be great if it could.

**Comment by ryanemax** [comment]
same issue, many situation we couldn't use GCM or APN, is there any way to support more Push Service?
- Progressive Web APP, via service woker?
- count.ly ?
- other?
